---
openapi: 3.1.0
paths:
  /portfolioAdvisor:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      summary: Welcome
      tags:
      - Portfolio Assistant Resource
    post:
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Advice
      tags:
      - Portfolio Assistant Resource
      security:
      - SecurityScheme:
        - StockTrader
        - StockViewer
  /portfolioAdvisor/streaming:
    post:
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  type: string
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      summary: Advice Streaming
      tags:
      - Portfolio Assistant Resource
      security:
      - SecurityScheme:
        - StockTrader
        - StockViewer
components:
  securitySchemes:
    SecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication
info:
  title: portfolioassistant API
  version: 1.0.1-SNAPSHOT
servers:
- url: http://localhost:8080
  description: Auto generated value
- url: http://0.0.0.0:8080
  description: Auto generated value
